# Site settings
title: Fontanería A Fondo | José Antonio Fondo Blanco
description: "Fontanería A Coruña"
baseurl: "" # the subpath of your site, e.g. /blog
url: "fontaneriafondo16.github.io" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Fontanería A Fondo
    hero_description: José Antonio Fondo Blanco

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 981 27 77 58
    emergency: 639 88 41 65
    email: fontaneriafondo@gmail.com
    address: Eladio Rodríguez 26 Bajo<br>A Coruña

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Eladio Rodriguez 26, A Coruña, España
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter:
instagram:
youtube:
skype:
feed: no

# Footer
copyright: © 2016 CDPC - Todos los derechos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
